steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}-${SHORT_SHA}', 
           '--build-arg', 'FIREBASE_REALTIMEDATABASE_URL=${_FIREBASE_REALTIMEDATABASE_URL}',
           '--build-arg', 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}',
           '--build-arg', 'FIREBASE_PROJECT_CLIENT_EMAIL=${_FIREBASE_PROJECT_CLIENT_EMAIL}',
           '--build-arg', 'FIREBASE_PROJECT_PRIVATE_KEY=${_FIREBASE_PROJECT_PRIVATE_KEY}',
           '--build-arg', 'AUTH_SALT=${_AUTH_SALT}',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}-${SHORT_SHA}']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['run', 'deploy', '${_SERVICE_NAME}',
           '--image', 'gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}-${SHORT_SHA}',
           '--region', '${_DEPLOY_REGION}']
options:
  logging: CLOUD_LOGGING_ONLY