FROM node:23-bookworm AS build

WORKDIR /app

COPY . /app
#RUN --mount=type=cache,target=/root/.npm npm install

ARG FIREBASE_REALTIMEDATABASE_URL
ENV FIREBASE_REALTIMEDATABASE_URL=$FIREBASE_REALTIMEDATABASE_URL

ARG FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID

ARG FIREBASE_PROJECT_CLIENT_EMAIL
ENV FIREBASE_PROJECT_CLIENT_EMAIL=$FIREBASE_PROJECT_CLIENT_EMAIL

ARG FIREBASE_PROJECT_PRIVATE_KEY
ENV FIREBASE_PROJECT_PRIVATE_KEY=$FIREBASE_PROJECT_PRIVATE_KEY

ARG AUTH_SALT
ENV AUTH_SALT=$AUTH_SALT

RUN env
RUN npm install
RUN npm run build

FROM node:23-bookworm-slim

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/build ./build

CMD ["node", "build"]